sudo: false
language: node_js
node_js:
    - "12"
cache:
    directories:
        - node_modules
script:
    - bash travis-ci.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./dist/
  repo: $DIST_REPO
  on:
    branch: master