export class ItemNames
{
    static readonly Randomizer: string[] = new Array();

    constructor() {
        ItemNames.Randomizer.push("NONE");
        ItemNames.Randomizer.push("Bombs (5)");
        ItemNames.Randomizer.push("Deku Nuts (5)");
        ItemNames.Randomizer.push("Bombchu (10)");
        ItemNames.Randomizer.push("Fairy Bow");
        ItemNames.Randomizer.push("Fairy Slingshot");
        ItemNames.Randomizer.push("Boomerang");
        ItemNames.Randomizer.push("Deku Stick");
        ItemNames.Randomizer.push("Hookshot");
        ItemNames.Randomizer.push("Longshot");
        ItemNames.Randomizer.push("Lens of Truth");
        ItemNames.Randomizer.push("Zelda's Letter");
        ItemNames.Randomizer.push("Ocarina of Time");
        ItemNames.Randomizer.push("Megaton Hammer");
        ItemNames.Randomizer.push("Cojiro");
        ItemNames.Randomizer.push("Empty Bottle");
        ItemNames.Randomizer.push("Red Potion");
        ItemNames.Randomizer.push("Green Potion");
        ItemNames.Randomizer.push("Blue Potion");
        ItemNames.Randomizer.push("Bottled Fairy");
        ItemNames.Randomizer.push("Bottled Lon Lon Milk");
        ItemNames.Randomizer.push("Bottled Ruto's Letter");
        ItemNames.Randomizer.push("Magic Bean");
        ItemNames.Randomizer.push("Skull Mask");
        ItemNames.Randomizer.push("Spooky Mask");
        ItemNames.Randomizer.push("Chicken");
        ItemNames.Randomizer.push("Keaton Mask");
        ItemNames.Randomizer.push("Bunny Hood");
        ItemNames.Randomizer.push("Mask of Truth");
        ItemNames.Randomizer.push("Pocket Egg");
        ItemNames.Randomizer.push("Pocket Cucco");
        ItemNames.Randomizer.push("Odd Mushroom");
        ItemNames.Randomizer.push("Odd Potion");
        ItemNames.Randomizer.push("Poacher's Saw");
        ItemNames.Randomizer.push("Goron's Sword (Broken)");
        ItemNames.Randomizer.push("Prescription");
        ItemNames.Randomizer.push("Eyeball Frog");
        ItemNames.Randomizer.push("Eye Drops");
        ItemNames.Randomizer.push("Claim Check");
        ItemNames.Randomizer.push("Kokiri Sword");
        ItemNames.Randomizer.push("Giant's Knife");
        ItemNames.Randomizer.push("Deku Shield");
        ItemNames.Randomizer.push("Hylian Shield");
        ItemNames.Randomizer.push("Mirror Shield");
        ItemNames.Randomizer.push("Goron Tunic");
        ItemNames.Randomizer.push("Zora Tunic");
        ItemNames.Randomizer.push("Iron Boots");
        ItemNames.Randomizer.push("Hover Boots");
        ItemNames.Randomizer.push("Big Quiver");
        ItemNames.Randomizer.push("Biggest Quiver");
        ItemNames.Randomizer.push("Bomb Bag");
        ItemNames.Randomizer.push("Big Bomb Bag");
        ItemNames.Randomizer.push("Biggest Bomb Bag");
        ItemNames.Randomizer.push("Silver Gauntlets");
        ItemNames.Randomizer.push("Golden Gauntlets");
        ItemNames.Randomizer.push("Silver Scale");
        ItemNames.Randomizer.push("Golden Scale");
        ItemNames.Randomizer.push("Stone of Agony");
        ItemNames.Randomizer.push("Gerudo Membership Card");
        ItemNames.Randomizer.push("Fairy Ocarina");
        ItemNames.Randomizer.push("Deku Seeds (5)");
        ItemNames.Randomizer.push("Heart Container");
        ItemNames.Randomizer.push("Piece of Heart");
        ItemNames.Randomizer.push("Boss Key");
        ItemNames.Randomizer.push("Compass");
        ItemNames.Randomizer.push("Map");
        ItemNames.Randomizer.push("Small Key");
        ItemNames.Randomizer.push("Small Magic Jar");
        ItemNames.Randomizer.push("Large Magic Jar");
        ItemNames.Randomizer.push("Adult's Wallet");
        ItemNames.Randomizer.push("Giant's Wallet");
        ItemNames.Randomizer.push("Weird Egg");
        ItemNames.Randomizer.push("Recovery Heart");
        ItemNames.Randomizer.push("Arrows (5)");
        ItemNames.Randomizer.push("Arrows (10)");
        ItemNames.Randomizer.push("Arrows (30)");
        ItemNames.Randomizer.push("Green Rupee");
        ItemNames.Randomizer.push("Blue Rupee");
        ItemNames.Randomizer.push("Red Rupee");
        ItemNames.Randomizer.push("Heart Container");
        ItemNames.Randomizer.push("Lon Lon Milk (Refill)");
        ItemNames.Randomizer.push("Goron Mask");
        ItemNames.Randomizer.push("Zora Mask");
        ItemNames.Randomizer.push("Gerudo Mask");
        ItemNames.Randomizer.push("Goron's Bracelet");
        ItemNames.Randomizer.push("Purple Rupee");
        ItemNames.Randomizer.push("Huge Rupee");
        ItemNames.Randomizer.push("Biggoron's Sword");
        ItemNames.Randomizer.push("Fire Arrow");
        ItemNames.Randomizer.push("Ice Arrow");
        ItemNames.Randomizer.push("Light Arrow");
        ItemNames.Randomizer.push("Gold Skulltula Token");
        ItemNames.Randomizer.push("Din's Fire");
        ItemNames.Randomizer.push("Farore's Wind");
        ItemNames.Randomizer.push("Nayru's Love");
        ItemNames.Randomizer.push("Bullet Bag (30)");
        ItemNames.Randomizer.push("Bullet Bag (40)");
        ItemNames.Randomizer.push("Deku Sticks (5)");
        ItemNames.Randomizer.push("Deku Sticks (10)");
        ItemNames.Randomizer.push("Deku Nuts (5)");
        ItemNames.Randomizer.push("Deku Nuts (10)");
        ItemNames.Randomizer.push("Bomb");
        ItemNames.Randomizer.push("Bombs (10)");
        ItemNames.Randomizer.push("Bombs (20)");
        ItemNames.Randomizer.push("Bombs (30)");
        ItemNames.Randomizer.push("Deku Seeds (30)");
        ItemNames.Randomizer.push("Bombchu (5)");
        ItemNames.Randomizer.push("Bombchu (20)");
        ItemNames.Randomizer.push("Fish (Refill)");
        ItemNames.Randomizer.push("Bugs (Refill)");
        ItemNames.Randomizer.push("Blue Fire (Refill)");
        ItemNames.Randomizer.push("Poe (Refill)");
        ItemNames.Randomizer.push("Big Poe (Refill)");
        ItemNames.Randomizer.push("Small Key (Chest Game)");
        ItemNames.Randomizer.push("Green Rupee (Chest Game)");
        ItemNames.Randomizer.push("Blue Rupee (Chest Game)");
        ItemNames.Randomizer.push("Red Rupee (Chest Game)");
        ItemNames.Randomizer.push("Purple Rupee (Chest Game)");
        ItemNames.Randomizer.push("Piece of Heart (Chest Game)");
        ItemNames.Randomizer.push("Deku Stick Upgrade (20)");
        ItemNames.Randomizer.push("Deku Stick Upgrade (30)");
        ItemNames.Randomizer.push("Deku Nut Upgrade (30)");
        ItemNames.Randomizer.push("Deku Nut Upgrade (40)");
        ItemNames.Randomizer.push("Bullet Bag (50)");
        ItemNames.Randomizer.push("Ice Trap");
        ItemNames.Randomizer.push("NONE");
        ItemNames.Randomizer.push("NONE");
        ItemNames.Randomizer.push("NONE");
        ItemNames.Randomizer.push("Progressive Hookshot");
        ItemNames.Randomizer.push("Progressive Strength");
        ItemNames.Randomizer.push("Progressive Bomb Bag");
        ItemNames.Randomizer.push("Progressive Bow");
        ItemNames.Randomizer.push("Progressive Slingshot");
        ItemNames.Randomizer.push("Progressive Wallet");
        ItemNames.Randomizer.push("Progressive Scale");
        ItemNames.Randomizer.push("Progressive Nut Capacity");
        ItemNames.Randomizer.push("Progressive Stick Capacity");
        ItemNames.Randomizer.push("Progressive Bombchus");
        ItemNames.Randomizer.push("Progressive Magic Meter");
        ItemNames.Randomizer.push("Progressive Ocarina");
        ItemNames.Randomizer.push("Bottle with Red Potion");
        ItemNames.Randomizer.push("Bottle with Green Potion");
        ItemNames.Randomizer.push("Bottle with Blue Potion");
        ItemNames.Randomizer.push("Bottle with Fairy");
        ItemNames.Randomizer.push("Bottle with Fish");
        ItemNames.Randomizer.push("Bottle with Blue Fire");
        ItemNames.Randomizer.push("Bottle with Bugs");
        ItemNames.Randomizer.push("Bottle with Big Poe");
        ItemNames.Randomizer.push("Bottle with Poe");
        ItemNames.Randomizer.push("Forest Temple Boss Key");
        ItemNames.Randomizer.push("Fire Temple Boss Key");
        ItemNames.Randomizer.push("Water Temple Boss Key");
        ItemNames.Randomizer.push("Spirit Temple Boss Key");
        ItemNames.Randomizer.push("Shadow Temple Boss Key");
        ItemNames.Randomizer.push("Ganon's Castle Boss Key");
        ItemNames.Randomizer.push("Deku Tree Compass");
        ItemNames.Randomizer.push("Dodongo's Cavern Compass");
        ItemNames.Randomizer.push("Jabu Jabu Compass");
        ItemNames.Randomizer.push("Forest Temple Compass");
        ItemNames.Randomizer.push("Fire Temple Compass");
        ItemNames.Randomizer.push("Water Temple Compass");
        ItemNames.Randomizer.push("Spirit Temple Compass");
        ItemNames.Randomizer.push("Shadow Temple Compass");
        ItemNames.Randomizer.push("Bottom of the Well Compass");
        ItemNames.Randomizer.push("Ice Cavern Compass");
        ItemNames.Randomizer.push("Deku Tree Map");
        ItemNames.Randomizer.push("Dodongo's Cavern Map");
        ItemNames.Randomizer.push("Jabu Jabu Map");
        ItemNames.Randomizer.push("Forest Temple Map");
        ItemNames.Randomizer.push("Fire Temple Map");
        ItemNames.Randomizer.push("Water Temple Map");
        ItemNames.Randomizer.push("Spirit Temple Map");
        ItemNames.Randomizer.push("Shadow Temple Map");
        ItemNames.Randomizer.push("Bottom of the Well Map");
        ItemNames.Randomizer.push("Ice Cavern Map");
        ItemNames.Randomizer.push("Forest Temple Small Key");
        ItemNames.Randomizer.push("Fire Temple Small Key");
        ItemNames.Randomizer.push("Water Temple Small Key");
        ItemNames.Randomizer.push("Spirit Temple Small Key");
        ItemNames.Randomizer.push("Shadow Temple Small Key");
        ItemNames.Randomizer.push("Bottom of the Well Small Key");
        ItemNames.Randomizer.push("Gerudo Training Small Key");
        ItemNames.Randomizer.push("Gerudo Fortress Small Key");
        ItemNames.Randomizer.push("Ganon's Castle Small Key");
        ItemNames.Randomizer.push("Double Defense");
        ItemNames.Randomizer.push("Magic Meter");
        ItemNames.Randomizer.push("Double Magic");
        ItemNames.Randomizer.push("Minuet of Forest");
        ItemNames.Randomizer.push("Bolero of Fire");
        ItemNames.Randomizer.push("Serenade of Water");
        ItemNames.Randomizer.push("Requiem of Spirit");
        ItemNames.Randomizer.push("Nocturn of Shadow");
        ItemNames.Randomizer.push("Prelude of Light");
        ItemNames.Randomizer.push("Zelda's Lullaby");
        ItemNames.Randomizer.push("Epona's Song");
        ItemNames.Randomizer.push("Saria's Song");
        ItemNames.Randomizer.push("Sun's Song");
        ItemNames.Randomizer.push("Song of Time");
        ItemNames.Randomizer.push("Song of Storms");
        ItemNames.Randomizer.push("Tycoon's Wallet");
        ItemNames.Randomizer.push("Redundant Letter Bottle");
        ItemNames.Randomizer.push("Magic Bean Pack");
    }
}

new ItemNames();